{
 "title": "Cephalocon Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "authority", "query": { "query": "query_result(s3_request_total)" } },
   { "name": "region", "query": { "query": "query_result(s3_request_total)" } },
   { "name": "costsstorage", "label": "Costs Storage", "query": "0.000001, 0.000005, 0.000010" },
   { "name": "coststraffic", "label": "Costs Traffic", "query": "0.00001,  0.00005, 0.00010" },
   { "name": "metricsinstances", "query": "${VAR_METRICSINSTANCES}" }
  ]
 },
 "panels": [
  {
   "title": "Topk per Bucket/User stats",
   "type": "heatmap",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(15, sum by (bucket, user) (rate(s3_request_total{authority=~\"$authority\", region=~\"$region\"}[5m])))",
     "legendFormat": "{{bucket}}/{{user}}"
    }
   ]
  },
  {
   "title": "Topk rate limited",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (bucket,user) (rate(s3_rate_limited_total{authority=~\"$authority\",region=~\"$region\"}[5m])))\n",
     "legendFormat": "{{bucket}}/{{user}}"
    }
   ]
  },
  {
   "title": "Topk payment limited",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (bucket,user) (rate(s3_payment_required_total{authority=~\"$authority\",region=~\"$region\"}[5m]))) * 100 or vector(0)",
     "legendFormat": "{{bucket}}/{{user}}"
    }
   ]
  },
  {
   "title": "Method",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (rate(s3_request_total{method!=\"unknown\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests per Region/24h",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (region) (count_over_time(s3_request_total{authority=~\"$authority\",region=~\"$region\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{envoy_cluster_name=~\".*\"})",
     "legendFormat": "connection"
    }
   ]
  },
  {
   "title": "Incoming Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=~\".*\"})",
     "legendFormat": "connection"
    }
   ]
  },
  {
   "title": "response code",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (envoy_response_code_class) (irate(envoy_listener_http_downstream_rq_xx{}[5m]))",
     "legendFormat": "{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Latency 95th percentile through Policy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (bucket, le) (rate(request_latency_seconds_bucket[5m])))",
     "legendFormat": "{{bucket}} {{name}}"
    }
   ]
  },
  {
   "title": "Latency 95th percentile per Policy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (name, le) (rate(request_latency_seconds_bucket[5m])))",
     "legendFormat": "{{bucket}} {{name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (name, le) (rate(redis_request_latency_seconds_bucket[5m]))) * -1",
     "legendFormat": "redis: {{name}}"
    }
   ]
  },
  {
   "title": "Costs traffic + storage / day",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (user) ((sum_over_time(s3_request_size_total{authority=~\"$authority\", region=~\"$region\"}[24h]) * ${coststraffic}) + sum_over_time(s3_request_total{authority=~\"$authority\", region=~\"$region\"}[24h])) * ${costsstorage}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Traffic per User / day",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (user) (sum_over_time(s3_request_size_total{authority=~\"$authority\", region=~\"$region\", user!~\"None\"}[24h])) / 1024",
     "legendFormat": "{{user}}"
    }
   ]
  }
 ]
}